
version: '3'

services:

 app:
   ports:
     - "80:80"
   build: ./docker/app
   container_name: CRUD_app
   volumes:
     - ./src:/var/www/html
 db:
   image: mysql:5.7
   container_name: CRUD_db
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: CRUD_db
     MYSQL_USER: CRUD_user
     MYSQL_PASSWORD: CRUD_pass
     TZ: 'Asia/Tokyo'

   command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

   volumes:
     - ./docker/db/data:/var/lib/mysql
     - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
   ports:
     - 3306:3306
 phpmyadmin:
  image: phpmyadmin/phpmyadmin:5

  container_name: CRUD_phpmyadmin

  links:
     - db
  ports:
     - 8080:80

  volumes:
     - ./docker/phpmyadmin/sessions:/sessions

 mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080